kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: demo-service-turbine
  name: demo-service-turbine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-turbine
  template:
    metadata:
      name: demo-service-turbine
      labels:
        app: demo-service-turbine
    spec:
      containers:
      - name: demo-service-turbine
        image: repository:5000/demo-service-turbine
        imagePullPolicy: Always
        env:
          - name: GIT_URL
            value: "http://demo-service-config:9000"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service-turbine
  name: demo-service-turbine
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9006 
    targetPort: 9006
    nodePort: 31006
  selector:
    app: demo-service-turbine
